### ISSUE TITLE
P-value not properly calculated for with k=0

### ISSUE THREAD

**Issue by mxmeier** [tudo-astroparticlephysics/pydisteval#23]
https://github.com/tudo-astroparticlephysics/pydisteval/blob/269d1ec22f8b5d8d005245d775c252d86a007af1/disteval/visualization/comparison_plotter/functions/calc_funcs.py#L521

In case of k=0 the p-value is set to `-np.inf`, which should not be the case, instead k=0 can be used in the general case calculation for the p-value.
The same thing is happening in some additional functions.

**Comment by mhuen** [comment]
Pull request #24 should fix this

**Comment by mhuen** [comment]
Pull request #24 is now merged to master branch, therefore closing this issue
